# Generated by Django 2.1.4 on 2019-02-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowlevel', '0003_alarm_cronjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='day',
            field=models.CharField(default='*', max_length=255),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='month',
            field=models.CharField(default='*', max_length=255),
        ),
    ]
