version: '3.7'
services:
  rpi_prod:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    ports:
      - "8888:8888"
      
  rpi_dev:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    ports:
      - "8888:8000"
    volumes:
      - type: bind
        source: ./app
        target: /home/pi/app/app/
    command: >-
      bash -c "
      cd /home/pi/app/app
      && python3 manage.py migrate
      && python3 manage.py runserver 0.0.0.0:8000 
      "