# Generated by Django 2.2.5 on 2019-09-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0004_auto_20190209_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='command',
            field=models.CharField(default='sudo python3 /home/pi/app/alarms/led_libs/start_alarm.py', max_length=255),
        ),
    ]
