# Generated by Django 2.2.5 on 2019-10-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0005_alarm_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='command',
            field=models.CharField(max_length=255),
        ),
    ]
